//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFacturaElectronica.PruebaConsola2.FactElectWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CbteAsoc", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class CbteAsoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TipoField;
        
        private int PtoVtaField;
        
        private long NroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int PtoVta {
            get {
                return this.PtoVtaField;
            }
            set {
                if ((this.PtoVtaField.Equals(value) != true)) {
                    this.PtoVtaField = value;
                    this.RaisePropertyChanged("PtoVta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long Nro {
            get {
                return this.NroField;
            }
            set {
                if ((this.NroField.Equals(value) != true)) {
                    this.NroField = value;
                    this.RaisePropertyChanged("Nro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tributo", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class Tributo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        private double BaseImpField;
        
        private double AlicField;
        
        private double ImporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double BaseImp {
            get {
                return this.BaseImpField;
            }
            set {
                if ((this.BaseImpField.Equals(value) != true)) {
                    this.BaseImpField = value;
                    this.RaisePropertyChanged("BaseImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Alic {
            get {
                return this.AlicField;
            }
            set {
                if ((this.AlicField.Equals(value) != true)) {
                    this.AlicField = value;
                    this.RaisePropertyChanged("Alic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlicIva", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class AlicIva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private double BaseImpField;
        
        private double ImporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double BaseImp {
            get {
                return this.BaseImpField;
            }
            set {
                if ((this.BaseImpField.Equals(value) != true)) {
                    this.BaseImpField = value;
                    this.RaisePropertyChanged("BaseImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opcional", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class Opcional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAEResponse", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class FECAEResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAECabResponse FeCabRespField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEDetResponse[] FeDetRespField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.Evt[] EventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.Err[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAECabResponse FeCabResp {
            get {
                return this.FeCabRespField;
            }
            set {
                if ((object.ReferenceEquals(this.FeCabRespField, value) != true)) {
                    this.FeCabRespField = value;
                    this.RaisePropertyChanged("FeCabResp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEDetResponse[] FeDetResp {
            get {
                return this.FeDetRespField;
            }
            set {
                if ((object.ReferenceEquals(this.FeDetRespField, value) != true)) {
                    this.FeDetRespField = value;
                    this.RaisePropertyChanged("FeDetResp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.Evt[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.Err[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAECabResponse", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class FECAECabResponse : TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECabResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAEDetResponse", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class FECAEDetResponse : TestFacturaElectronica.PruebaConsola2.FactElectWCF.FEDetResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAEFchVtoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CAE {
            get {
                return this.CAEField;
            }
            set {
                if ((object.ReferenceEquals(this.CAEField, value) != true)) {
                    this.CAEField = value;
                    this.RaisePropertyChanged("CAE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CAEFchVto {
            get {
                return this.CAEFchVtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CAEFchVtoField, value) != true)) {
                    this.CAEFchVtoField = value;
                    this.RaisePropertyChanged("CAEFchVto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evt", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class Evt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Err", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class Err : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECabResponse", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEACabResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAECabResponse))]
    public partial class FECabResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long CuitField;
        
        private int PtoVtaField;
        
        private int CbteTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FchProcesoField;
        
        private int CantRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReprocesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Cuit {
            get {
                return this.CuitField;
            }
            set {
                if ((this.CuitField.Equals(value) != true)) {
                    this.CuitField = value;
                    this.RaisePropertyChanged("Cuit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PtoVta {
            get {
                return this.PtoVtaField;
            }
            set {
                if ((this.PtoVtaField.Equals(value) != true)) {
                    this.PtoVtaField = value;
                    this.RaisePropertyChanged("PtoVta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CbteTipo {
            get {
                return this.CbteTipoField;
            }
            set {
                if ((this.CbteTipoField.Equals(value) != true)) {
                    this.CbteTipoField = value;
                    this.RaisePropertyChanged("CbteTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FchProceso {
            get {
                return this.FchProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.FchProcesoField, value) != true)) {
                    this.FchProcesoField = value;
                    this.RaisePropertyChanged("FchProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CantReg {
            get {
                return this.CantRegField;
            }
            set {
                if ((this.CantRegField.Equals(value) != true)) {
                    this.CantRegField = value;
                    this.RaisePropertyChanged("CantReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Reproceso {
            get {
                return this.ReprocesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReprocesoField, value) != true)) {
                    this.ReprocesoField = value;
                    this.RaisePropertyChanged("Reproceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAEACabResponse", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class FECAEACabResponse : TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECabResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FEDetResponse", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEADetResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEDetResponse))]
    public partial class FEDetResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ConceptoField;
        
        private int DocTipoField;
        
        private long DocNroField;
        
        private long CbteDesdeField;
        
        private long CbteHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CbteFchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.Obs[] ObservacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Concepto {
            get {
                return this.ConceptoField;
            }
            set {
                if ((this.ConceptoField.Equals(value) != true)) {
                    this.ConceptoField = value;
                    this.RaisePropertyChanged("Concepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DocTipo {
            get {
                return this.DocTipoField;
            }
            set {
                if ((this.DocTipoField.Equals(value) != true)) {
                    this.DocTipoField = value;
                    this.RaisePropertyChanged("DocTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long DocNro {
            get {
                return this.DocNroField;
            }
            set {
                if ((this.DocNroField.Equals(value) != true)) {
                    this.DocNroField = value;
                    this.RaisePropertyChanged("DocNro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long CbteDesde {
            get {
                return this.CbteDesdeField;
            }
            set {
                if ((this.CbteDesdeField.Equals(value) != true)) {
                    this.CbteDesdeField = value;
                    this.RaisePropertyChanged("CbteDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long CbteHasta {
            get {
                return this.CbteHastaField;
            }
            set {
                if ((this.CbteHastaField.Equals(value) != true)) {
                    this.CbteHastaField = value;
                    this.RaisePropertyChanged("CbteHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CbteFch {
            get {
                return this.CbteFchField;
            }
            set {
                if ((object.ReferenceEquals(this.CbteFchField, value) != true)) {
                    this.CbteFchField = value;
                    this.RaisePropertyChanged("CbteFch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.Obs[] Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAEADetResponse", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class FECAEADetResponse : TestFacturaElectronica.PruebaConsola2.FactElectWCF.FEDetResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAEAField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CAEA {
            get {
                return this.CAEAField;
            }
            set {
                if ((object.ReferenceEquals(this.CAEAField, value) != true)) {
                    this.CAEAField = value;
                    this.RaisePropertyChanged("CAEA");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Obs", Namespace="http://ar.gov.afip.dif.FEV1/")]
    [System.SerializableAttribute()]
    public partial class Obs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FactElectWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AutorizarConWSAA", ReplyAction="http://tempuri.org/IService1/AutorizarConWSAAResponse")]
        void AutorizarConWSAA(string _rutaCertificado, long _cuit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfeccionarCabecera", ReplyAction="http://tempuri.org/IService1/ConfeccionarCabeceraResponse")]
        void ConfeccionarCabecera(int _cantReg, int _ptoVta, int _cbteTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfeccionarDetalle", ReplyAction="http://tempuri.org/IService1/ConfeccionarDetalleResponse")]
        void ConfeccionarDetalle(
                    int _concepto, 
                    int _docTipo, 
                    long _docNro, 
                    System.DateTime _cbteFch, 
                    double _impTotal, 
                    double _impTotConc, 
                    double _impNeto, 
                    double _impIVA, 
                    double _impOpEx, 
                    double _impTrib, 
                    System.DateTime _fchServDesde, 
                    System.DateTime _fchServHasta, 
                    System.DateTime _fchVtoPago, 
                    string _monId, 
                    double _monCotiz, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.CbteAsoc[] _cbtesAsoc, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.Tributo[] _tributo, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.AlicIva[] _iva, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.Opcional[] _opcionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AutorizarFactura", ReplyAction="http://tempuri.org/IService1/AutorizarFacturaResponse")]
        void AutorizarFactura();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LeerRespuesta", ReplyAction="http://tempuri.org/IService1/LeerRespuestaResponse")]
        TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEResponse LeerRespuesta();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TestFacturaElectronica.PruebaConsola2.FactElectWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TestFacturaElectronica.PruebaConsola2.FactElectWCF.IService1>, TestFacturaElectronica.PruebaConsola2.FactElectWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AutorizarConWSAA(string _rutaCertificado, long _cuit) {
            base.Channel.AutorizarConWSAA(_rutaCertificado, _cuit);
        }
        
        public void ConfeccionarCabecera(int _cantReg, int _ptoVta, int _cbteTipo) {
            base.Channel.ConfeccionarCabecera(_cantReg, _ptoVta, _cbteTipo);
        }
        
        public void ConfeccionarDetalle(
                    int _concepto, 
                    int _docTipo, 
                    long _docNro, 
                    System.DateTime _cbteFch, 
                    double _impTotal, 
                    double _impTotConc, 
                    double _impNeto, 
                    double _impIVA, 
                    double _impOpEx, 
                    double _impTrib, 
                    System.DateTime _fchServDesde, 
                    System.DateTime _fchServHasta, 
                    System.DateTime _fchVtoPago, 
                    string _monId, 
                    double _monCotiz, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.CbteAsoc[] _cbtesAsoc, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.Tributo[] _tributo, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.AlicIva[] _iva, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.Opcional[] _opcionales) {
            base.Channel.ConfeccionarDetalle(_concepto, _docTipo, _docNro, _cbteFch, _impTotal, _impTotConc, _impNeto, _impIVA, _impOpEx, _impTrib, _fchServDesde, _fchServHasta, _fchVtoPago, _monId, _monCotiz, _cbtesAsoc, _tributo, _iva, _opcionales);
        }
        
        public void AutorizarFactura() {
            base.Channel.AutorizarFactura();
        }
        
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEResponse LeerRespuesta() {
            return base.Channel.LeerRespuesta();
        }
    }
}
