//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.0
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFacturaElectronica.PruebaConsola2.FactElectWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CbteAsoc", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class CbteAsoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long nroFieldField;
        
        private int ptoVtaFieldField;
        
        private int tipoFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long nroField {
            get {
                return this.nroFieldField;
            }
            set {
                if ((this.nroFieldField.Equals(value) != true)) {
                    this.nroFieldField = value;
                    this.RaisePropertyChanged("nroField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ptoVtaField {
            get {
                return this.ptoVtaFieldField;
            }
            set {
                if ((this.ptoVtaFieldField.Equals(value) != true)) {
                    this.ptoVtaFieldField = value;
                    this.RaisePropertyChanged("ptoVtaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int tipoField {
            get {
                return this.tipoFieldField;
            }
            set {
                if ((this.tipoFieldField.Equals(value) != true)) {
                    this.tipoFieldField = value;
                    this.RaisePropertyChanged("tipoField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tributo", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class Tributo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double alicFieldField;
        
        private double baseImpFieldField;
        
        private string descFieldField;
        
        private short idFieldField;
        
        private double importeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double alicField {
            get {
                return this.alicFieldField;
            }
            set {
                if ((this.alicFieldField.Equals(value) != true)) {
                    this.alicFieldField = value;
                    this.RaisePropertyChanged("alicField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double baseImpField {
            get {
                return this.baseImpFieldField;
            }
            set {
                if ((this.baseImpFieldField.Equals(value) != true)) {
                    this.baseImpFieldField = value;
                    this.RaisePropertyChanged("baseImpField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descField {
            get {
                return this.descFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.descFieldField, value) != true)) {
                    this.descFieldField = value;
                    this.RaisePropertyChanged("descField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short idField {
            get {
                return this.idFieldField;
            }
            set {
                if ((this.idFieldField.Equals(value) != true)) {
                    this.idFieldField = value;
                    this.RaisePropertyChanged("idField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double importeField {
            get {
                return this.importeFieldField;
            }
            set {
                if ((this.importeFieldField.Equals(value) != true)) {
                    this.importeFieldField = value;
                    this.RaisePropertyChanged("importeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlicIva", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class AlicIva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double baseImpFieldField;
        
        private int idFieldField;
        
        private double importeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double baseImpField {
            get {
                return this.baseImpFieldField;
            }
            set {
                if ((this.baseImpFieldField.Equals(value) != true)) {
                    this.baseImpFieldField = value;
                    this.RaisePropertyChanged("baseImpField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idField {
            get {
                return this.idFieldField;
            }
            set {
                if ((this.idFieldField.Equals(value) != true)) {
                    this.idFieldField = value;
                    this.RaisePropertyChanged("idField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double importeField {
            get {
                return this.importeFieldField;
            }
            set {
                if ((this.importeFieldField.Equals(value) != true)) {
                    this.importeFieldField = value;
                    this.RaisePropertyChanged("importeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opcional", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class Opcional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string idFieldField;
        
        private string valorFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idField {
            get {
                return this.idFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.idFieldField, value) != true)) {
                    this.idFieldField = value;
                    this.RaisePropertyChanged("idField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorField {
            get {
                return this.valorFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.valorFieldField, value) != true)) {
                    this.valorFieldField = value;
                    this.RaisePropertyChanged("valorField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAEResponse", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class FECAEResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.Err[] errorsFieldField;
        
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.Evt[] eventsFieldField;
        
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAECabResponse feCabRespFieldField;
        
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEDetResponse[] feDetRespFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.Err[] errorsField {
            get {
                return this.errorsFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.errorsFieldField, value) != true)) {
                    this.errorsFieldField = value;
                    this.RaisePropertyChanged("errorsField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.Evt[] eventsField {
            get {
                return this.eventsFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.eventsFieldField, value) != true)) {
                    this.eventsFieldField = value;
                    this.RaisePropertyChanged("eventsField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAECabResponse feCabRespField {
            get {
                return this.feCabRespFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.feCabRespFieldField, value) != true)) {
                    this.feCabRespFieldField = value;
                    this.RaisePropertyChanged("feCabRespField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEDetResponse[] feDetRespField {
            get {
                return this.feDetRespFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.feDetRespFieldField, value) != true)) {
                    this.feDetRespFieldField = value;
                    this.RaisePropertyChanged("feDetRespField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAECabResponse", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class FECAECabResponse : TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECabResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Err", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class Err : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codeFieldField;
        
        private string msgFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codeField {
            get {
                return this.codeFieldField;
            }
            set {
                if ((this.codeFieldField.Equals(value) != true)) {
                    this.codeFieldField = value;
                    this.RaisePropertyChanged("codeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string msgField {
            get {
                return this.msgFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.msgFieldField, value) != true)) {
                    this.msgFieldField = value;
                    this.RaisePropertyChanged("msgField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evt", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class Evt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codeFieldField;
        
        private string msgFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codeField {
            get {
                return this.codeFieldField;
            }
            set {
                if ((this.codeFieldField.Equals(value) != true)) {
                    this.codeFieldField = value;
                    this.RaisePropertyChanged("codeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string msgField {
            get {
                return this.msgFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.msgFieldField, value) != true)) {
                    this.msgFieldField = value;
                    this.RaisePropertyChanged("msgField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAEDetResponse", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class FECAEDetResponse : TestFacturaElectronica.PruebaConsola2.FactElectWCF.FEDetResponse {
        
        private string cAEFchVtoFieldField;
        
        private string cAEFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cAEFchVtoField {
            get {
                return this.cAEFchVtoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.cAEFchVtoFieldField, value) != true)) {
                    this.cAEFchVtoFieldField = value;
                    this.RaisePropertyChanged("cAEFchVtoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cAEField {
            get {
                return this.cAEFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.cAEFieldField, value) != true)) {
                    this.cAEFieldField = value;
                    this.RaisePropertyChanged("cAEField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECabResponse", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAECabResponse))]
    public partial class FECabResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int cantRegFieldField;
        
        private int cbteTipoFieldField;
        
        private long cuitFieldField;
        
        private string fchProcesoFieldField;
        
        private int ptoVtaFieldField;
        
        private string reprocesoFieldField;
        
        private string resultadoFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cantRegField {
            get {
                return this.cantRegFieldField;
            }
            set {
                if ((this.cantRegFieldField.Equals(value) != true)) {
                    this.cantRegFieldField = value;
                    this.RaisePropertyChanged("cantRegField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cbteTipoField {
            get {
                return this.cbteTipoFieldField;
            }
            set {
                if ((this.cbteTipoFieldField.Equals(value) != true)) {
                    this.cbteTipoFieldField = value;
                    this.RaisePropertyChanged("cbteTipoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long cuitField {
            get {
                return this.cuitFieldField;
            }
            set {
                if ((this.cuitFieldField.Equals(value) != true)) {
                    this.cuitFieldField = value;
                    this.RaisePropertyChanged("cuitField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fchProcesoField {
            get {
                return this.fchProcesoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.fchProcesoFieldField, value) != true)) {
                    this.fchProcesoFieldField = value;
                    this.RaisePropertyChanged("fchProcesoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ptoVtaField {
            get {
                return this.ptoVtaFieldField;
            }
            set {
                if ((this.ptoVtaFieldField.Equals(value) != true)) {
                    this.ptoVtaFieldField = value;
                    this.RaisePropertyChanged("ptoVtaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string reprocesoField {
            get {
                return this.reprocesoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.reprocesoFieldField, value) != true)) {
                    this.reprocesoFieldField = value;
                    this.RaisePropertyChanged("reprocesoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string resultadoField {
            get {
                return this.resultadoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoFieldField, value) != true)) {
                    this.resultadoFieldField = value;
                    this.RaisePropertyChanged("resultadoField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FEDetResponse", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEDetResponse))]
    public partial class FEDetResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long cbteDesdeFieldField;
        
        private string cbteFchFieldField;
        
        private long cbteHastaFieldField;
        
        private int conceptoFieldField;
        
        private long docNroFieldField;
        
        private int docTipoFieldField;
        
        private TestFacturaElectronica.PruebaConsola2.FactElectWCF.Obs[] observacionesFieldField;
        
        private string resultadoFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long cbteDesdeField {
            get {
                return this.cbteDesdeFieldField;
            }
            set {
                if ((this.cbteDesdeFieldField.Equals(value) != true)) {
                    this.cbteDesdeFieldField = value;
                    this.RaisePropertyChanged("cbteDesdeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cbteFchField {
            get {
                return this.cbteFchFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.cbteFchFieldField, value) != true)) {
                    this.cbteFchFieldField = value;
                    this.RaisePropertyChanged("cbteFchField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long cbteHastaField {
            get {
                return this.cbteHastaFieldField;
            }
            set {
                if ((this.cbteHastaFieldField.Equals(value) != true)) {
                    this.cbteHastaFieldField = value;
                    this.RaisePropertyChanged("cbteHastaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int conceptoField {
            get {
                return this.conceptoFieldField;
            }
            set {
                if ((this.conceptoFieldField.Equals(value) != true)) {
                    this.conceptoFieldField = value;
                    this.RaisePropertyChanged("conceptoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long docNroField {
            get {
                return this.docNroFieldField;
            }
            set {
                if ((this.docNroFieldField.Equals(value) != true)) {
                    this.docNroFieldField = value;
                    this.RaisePropertyChanged("docNroField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int docTipoField {
            get {
                return this.docTipoFieldField;
            }
            set {
                if ((this.docTipoFieldField.Equals(value) != true)) {
                    this.docTipoFieldField = value;
                    this.RaisePropertyChanged("docTipoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.Obs[] observacionesField {
            get {
                return this.observacionesFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionesFieldField, value) != true)) {
                    this.observacionesFieldField = value;
                    this.RaisePropertyChanged("observacionesField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string resultadoField {
            get {
                return this.resultadoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoFieldField, value) != true)) {
                    this.resultadoFieldField = value;
                    this.RaisePropertyChanged("resultadoField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Obs", Namespace="http://schemas.datacontract.org/2004/07/TestFacturaElectronica.Dominio.FacturaEle" +
        "ctronicaWS")]
    [System.SerializableAttribute()]
    public partial class Obs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codeFieldField;
        
        private string msgFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codeField {
            get {
                return this.codeFieldField;
            }
            set {
                if ((this.codeFieldField.Equals(value) != true)) {
                    this.codeFieldField = value;
                    this.RaisePropertyChanged("codeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string msgField {
            get {
                return this.msgFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.msgFieldField, value) != true)) {
                    this.msgFieldField = value;
                    this.RaisePropertyChanged("msgField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FactElectWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AutorizarConWSAA", ReplyAction="http://tempuri.org/IService1/AutorizarConWSAAResponse")]
        void AutorizarConWSAA(string _rutaCertificado, long _cuit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfeccionarCabecera", ReplyAction="http://tempuri.org/IService1/ConfeccionarCabeceraResponse")]
        void ConfeccionarCabecera(int _cantReg, int _ptoVta, int _cbteTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfeccionarDetalle", ReplyAction="http://tempuri.org/IService1/ConfeccionarDetalleResponse")]
        void ConfeccionarDetalle(
                    int _concepto, 
                    int _docTipo, 
                    long _docNro, 
                    System.DateTime _cbteFch, 
                    double _impTotal, 
                    double _impTotConc, 
                    double _impNeto, 
                    double _impIVA, 
                    double _impOpEx, 
                    double _impTrib, 
                    System.DateTime _fchServDesde, 
                    System.DateTime _fchServHasta, 
                    System.DateTime _fchVtoPago, 
                    string _monId, 
                    double _monCotiz, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.CbteAsoc[] _cbtesAsoc, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.Tributo[] _tributo, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.AlicIva[] _iva, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.Opcional[] _opcionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AutorizarFactura", ReplyAction="http://tempuri.org/IService1/AutorizarFacturaResponse")]
        void AutorizarFactura();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LeerRespuesta", ReplyAction="http://tempuri.org/IService1/LeerRespuestaResponse")]
        TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEResponse LeerRespuesta();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TestFacturaElectronica.PruebaConsola2.FactElectWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TestFacturaElectronica.PruebaConsola2.FactElectWCF.IService1>, TestFacturaElectronica.PruebaConsola2.FactElectWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AutorizarConWSAA(string _rutaCertificado, long _cuit) {
            base.Channel.AutorizarConWSAA(_rutaCertificado, _cuit);
        }
        
        public void ConfeccionarCabecera(int _cantReg, int _ptoVta, int _cbteTipo) {
            base.Channel.ConfeccionarCabecera(_cantReg, _ptoVta, _cbteTipo);
        }
        
        public void ConfeccionarDetalle(
                    int _concepto, 
                    int _docTipo, 
                    long _docNro, 
                    System.DateTime _cbteFch, 
                    double _impTotal, 
                    double _impTotConc, 
                    double _impNeto, 
                    double _impIVA, 
                    double _impOpEx, 
                    double _impTrib, 
                    System.DateTime _fchServDesde, 
                    System.DateTime _fchServHasta, 
                    System.DateTime _fchVtoPago, 
                    string _monId, 
                    double _monCotiz, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.CbteAsoc[] _cbtesAsoc, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.Tributo[] _tributo, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.AlicIva[] _iva, 
                    TestFacturaElectronica.PruebaConsola2.FactElectWCF.Opcional[] _opcionales) {
            base.Channel.ConfeccionarDetalle(_concepto, _docTipo, _docNro, _cbteFch, _impTotal, _impTotConc, _impNeto, _impIVA, _impOpEx, _impTrib, _fchServDesde, _fchServHasta, _fchVtoPago, _monId, _monCotiz, _cbtesAsoc, _tributo, _iva, _opcionales);
        }
        
        public void AutorizarFactura() {
            base.Channel.AutorizarFactura();
        }
        
        public TestFacturaElectronica.PruebaConsola2.FactElectWCF.FECAEResponse LeerRespuesta() {
            return base.Channel.LeerRespuesta();
        }
    }
}
