//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.0
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFacturaElectronica.PruebaConsola.localhost {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CantRegistrosField;
        
        private int PuntoVentaField;
        
        private int TipoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Detalle> DetalleFacturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CantRegistros {
            get {
                return this.CantRegistrosField;
            }
            set {
                if ((this.CantRegistrosField.Equals(value) != true)) {
                    this.CantRegistrosField = value;
                    this.RaisePropertyChanged("CantRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PuntoVenta {
            get {
                return this.PuntoVentaField;
            }
            set {
                if ((this.PuntoVentaField.Equals(value) != true)) {
                    this.PuntoVentaField = value;
                    this.RaisePropertyChanged("PuntoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoComprobante {
            get {
                return this.TipoComprobanteField;
            }
            set {
                if ((this.TipoComprobanteField.Equals(value) != true)) {
                    this.TipoComprobanteField = value;
                    this.RaisePropertyChanged("TipoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Detalle> DetalleFactura {
            get {
                return this.DetalleFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleFacturaField, value) != true)) {
                    this.DetalleFacturaField = value;
                    this.RaisePropertyChanged("DetalleFactura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detalle", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class Detalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ConceptoField;
        
        private int DocTipoField;
        
        private long DocNroField;
        
        private System.DateTime FechaCompField;
        
        private double ImporteTotalField;
        
        private double ImporteTotalConcField;
        
        private double ImporteNetoField;
        
        private double ImporteIVAField;
        
        private double ImporteOpExentoField;
        
        private double ImporteTribField;
        
        private System.DateTime FechaServDesdeField;
        
        private System.DateTime FechaServHastaField;
        
        private System.DateTime FechaVtoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaIdField;
        
        private double MonedaCotizField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.CbteAsoc> CbtesAsocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Tributo> TributosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.AlicIva> IvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Opcional> OpcionalesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Concepto {
            get {
                return this.ConceptoField;
            }
            set {
                if ((this.ConceptoField.Equals(value) != true)) {
                    this.ConceptoField = value;
                    this.RaisePropertyChanged("Concepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DocTipo {
            get {
                return this.DocTipoField;
            }
            set {
                if ((this.DocTipoField.Equals(value) != true)) {
                    this.DocTipoField = value;
                    this.RaisePropertyChanged("DocTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long DocNro {
            get {
                return this.DocNroField;
            }
            set {
                if ((this.DocNroField.Equals(value) != true)) {
                    this.DocNroField = value;
                    this.RaisePropertyChanged("DocNro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaComp {
            get {
                return this.FechaCompField;
            }
            set {
                if ((this.FechaCompField.Equals(value) != true)) {
                    this.FechaCompField = value;
                    this.RaisePropertyChanged("FechaComp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double ImporteTotal {
            get {
                return this.ImporteTotalField;
            }
            set {
                if ((this.ImporteTotalField.Equals(value) != true)) {
                    this.ImporteTotalField = value;
                    this.RaisePropertyChanged("ImporteTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double ImporteTotalConc {
            get {
                return this.ImporteTotalConcField;
            }
            set {
                if ((this.ImporteTotalConcField.Equals(value) != true)) {
                    this.ImporteTotalConcField = value;
                    this.RaisePropertyChanged("ImporteTotalConc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double ImporteNeto {
            get {
                return this.ImporteNetoField;
            }
            set {
                if ((this.ImporteNetoField.Equals(value) != true)) {
                    this.ImporteNetoField = value;
                    this.RaisePropertyChanged("ImporteNeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double ImporteIVA {
            get {
                return this.ImporteIVAField;
            }
            set {
                if ((this.ImporteIVAField.Equals(value) != true)) {
                    this.ImporteIVAField = value;
                    this.RaisePropertyChanged("ImporteIVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double ImporteOpExento {
            get {
                return this.ImporteOpExentoField;
            }
            set {
                if ((this.ImporteOpExentoField.Equals(value) != true)) {
                    this.ImporteOpExentoField = value;
                    this.RaisePropertyChanged("ImporteOpExento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double ImporteTrib {
            get {
                return this.ImporteTribField;
            }
            set {
                if ((this.ImporteTribField.Equals(value) != true)) {
                    this.ImporteTribField = value;
                    this.RaisePropertyChanged("ImporteTrib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime FechaServDesde {
            get {
                return this.FechaServDesdeField;
            }
            set {
                if ((this.FechaServDesdeField.Equals(value) != true)) {
                    this.FechaServDesdeField = value;
                    this.RaisePropertyChanged("FechaServDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime FechaServHasta {
            get {
                return this.FechaServHastaField;
            }
            set {
                if ((this.FechaServHastaField.Equals(value) != true)) {
                    this.FechaServHastaField = value;
                    this.RaisePropertyChanged("FechaServHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime FechaVtoPago {
            get {
                return this.FechaVtoPagoField;
            }
            set {
                if ((this.FechaVtoPagoField.Equals(value) != true)) {
                    this.FechaVtoPagoField = value;
                    this.RaisePropertyChanged("FechaVtoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string MonedaId {
            get {
                return this.MonedaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaIdField, value) != true)) {
                    this.MonedaIdField = value;
                    this.RaisePropertyChanged("MonedaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public double MonedaCotiz {
            get {
                return this.MonedaCotizField;
            }
            set {
                if ((this.MonedaCotizField.Equals(value) != true)) {
                    this.MonedaCotizField = value;
                    this.RaisePropertyChanged("MonedaCotiz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.CbteAsoc> CbtesAsoc {
            get {
                return this.CbtesAsocField;
            }
            set {
                if ((object.ReferenceEquals(this.CbtesAsocField, value) != true)) {
                    this.CbtesAsocField = value;
                    this.RaisePropertyChanged("CbtesAsoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Tributo> Tributos {
            get {
                return this.TributosField;
            }
            set {
                if ((object.ReferenceEquals(this.TributosField, value) != true)) {
                    this.TributosField = value;
                    this.RaisePropertyChanged("Tributos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.AlicIva> Iva {
            get {
                return this.IvaField;
            }
            set {
                if ((object.ReferenceEquals(this.IvaField, value) != true)) {
                    this.IvaField = value;
                    this.RaisePropertyChanged("Iva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Opcional> Opcionales {
            get {
                return this.OpcionalesField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcionalesField, value) != true)) {
                    this.OpcionalesField = value;
                    this.RaisePropertyChanged("Opcionales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CbteAsoc", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class CbteAsoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        private int TipoField;
        
        private int PtoVtaField;
        
        private long NroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PtoVta {
            get {
                return this.PtoVtaField;
            }
            set {
                if ((this.PtoVtaField.Equals(value) != true)) {
                    this.PtoVtaField = value;
                    this.RaisePropertyChanged("PtoVta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Nro {
            get {
                return this.NroField;
            }
            set {
                if ((this.NroField.Equals(value) != true)) {
                    this.NroField = value;
                    this.RaisePropertyChanged("Nro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tributo", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class Tributo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        private double BaseImpField;
        
        private double AlicField;
        
        private double ImporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double BaseImp {
            get {
                return this.BaseImpField;
            }
            set {
                if ((this.BaseImpField.Equals(value) != true)) {
                    this.BaseImpField = value;
                    this.RaisePropertyChanged("BaseImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Alic {
            get {
                return this.AlicField;
            }
            set {
                if ((this.AlicField.Equals(value) != true)) {
                    this.AlicField = value;
                    this.RaisePropertyChanged("Alic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlicIva", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class AlicIva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        private int IdField;
        
        private double BaseImpField;
        
        private double ImporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double BaseImp {
            get {
                return this.BaseImpField;
            }
            set {
                if ((this.BaseImpField.Equals(value) != true)) {
                    this.BaseImpField = value;
                    this.RaisePropertyChanged("BaseImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opcional", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class Opcional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAEResponse", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class FECAEResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.FECAECabResponse FeCabRespField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.FECAEDetResponse> FeDetRespField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Evt> EventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Err> ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.FECAECabResponse FeCabResp {
            get {
                return this.FeCabRespField;
            }
            set {
                if ((object.ReferenceEquals(this.FeCabRespField, value) != true)) {
                    this.FeCabRespField = value;
                    this.RaisePropertyChanged("FeCabResp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.FECAEDetResponse> FeDetResp {
            get {
                return this.FeDetRespField;
            }
            set {
                if ((object.ReferenceEquals(this.FeDetRespField, value) != true)) {
                    this.FeDetRespField = value;
                    this.RaisePropertyChanged("FeDetResp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Evt> Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Err> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAECabResponse", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class FECAECabResponse : TestFacturaElectronica.PruebaConsola.localhost.FECabResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECAEDetResponse", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class FECAEDetResponse : TestFacturaElectronica.PruebaConsola.localhost.FEDetResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAEFchVtoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CAE {
            get {
                return this.CAEField;
            }
            set {
                if ((object.ReferenceEquals(this.CAEField, value) != true)) {
                    this.CAEField = value;
                    this.RaisePropertyChanged("CAE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CAEFchVto {
            get {
                return this.CAEFchVtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CAEFchVtoField, value) != true)) {
                    this.CAEFchVtoField = value;
                    this.RaisePropertyChanged("CAEFchVto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evt", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class Evt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Err", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class Err : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FECabResponse", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFacturaElectronica.PruebaConsola.localhost.FECAECabResponse))]
    public partial class FECabResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        private long CuitField;
        
        private int PtoVtaField;
        
        private int CbteTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FchProcesoField;
        
        private int CantRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReprocesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Cuit {
            get {
                return this.CuitField;
            }
            set {
                if ((this.CuitField.Equals(value) != true)) {
                    this.CuitField = value;
                    this.RaisePropertyChanged("Cuit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PtoVta {
            get {
                return this.PtoVtaField;
            }
            set {
                if ((this.PtoVtaField.Equals(value) != true)) {
                    this.PtoVtaField = value;
                    this.RaisePropertyChanged("PtoVta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CbteTipo {
            get {
                return this.CbteTipoField;
            }
            set {
                if ((this.CbteTipoField.Equals(value) != true)) {
                    this.CbteTipoField = value;
                    this.RaisePropertyChanged("CbteTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FchProceso {
            get {
                return this.FchProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.FchProcesoField, value) != true)) {
                    this.FchProcesoField = value;
                    this.RaisePropertyChanged("FchProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CantReg {
            get {
                return this.CantRegField;
            }
            set {
                if ((this.CantRegField.Equals(value) != true)) {
                    this.CantRegField = value;
                    this.RaisePropertyChanged("CantReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Reproceso {
            get {
                return this.ReprocesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReprocesoField, value) != true)) {
                    this.ReprocesoField = value;
                    this.RaisePropertyChanged("Reproceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FEDetResponse", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestFacturaElectronica.PruebaConsola.localhost.FECAEDetResponse))]
    public partial class FEDetResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        private int ConceptoField;
        
        private int DocTipoField;
        
        private long DocNroField;
        
        private long CbteDesdeField;
        
        private long CbteHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CbteFchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Obs> ObservacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Concepto {
            get {
                return this.ConceptoField;
            }
            set {
                if ((this.ConceptoField.Equals(value) != true)) {
                    this.ConceptoField = value;
                    this.RaisePropertyChanged("Concepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DocTipo {
            get {
                return this.DocTipoField;
            }
            set {
                if ((this.DocTipoField.Equals(value) != true)) {
                    this.DocTipoField = value;
                    this.RaisePropertyChanged("DocTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long DocNro {
            get {
                return this.DocNroField;
            }
            set {
                if ((this.DocNroField.Equals(value) != true)) {
                    this.DocNroField = value;
                    this.RaisePropertyChanged("DocNro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long CbteDesde {
            get {
                return this.CbteDesdeField;
            }
            set {
                if ((this.CbteDesdeField.Equals(value) != true)) {
                    this.CbteDesdeField = value;
                    this.RaisePropertyChanged("CbteDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long CbteHasta {
            get {
                return this.CbteHastaField;
            }
            set {
                if ((this.CbteHastaField.Equals(value) != true)) {
                    this.CbteHastaField = value;
                    this.RaisePropertyChanged("CbteHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CbteFch {
            get {
                return this.CbteFchField;
            }
            set {
                if ((object.ReferenceEquals(this.CbteFchField, value) != true)) {
                    this.CbteFchField = value;
                    this.RaisePropertyChanged("CbteFch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public System.Collections.Generic.List<TestFacturaElectronica.PruebaConsola.localhost.Obs> Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Obs", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    [System.SerializableAttribute()]
    public partial class Obs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1Field;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TestFacturaElectronica.PruebaConsola.localhost.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1", ConfigurationName="localhost.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/TestFacturaElectronica/WebService/WebService1 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestFacturaElectronica/WebService/WebService1/HelloWorld", ReplyAction="*")]
        TestFacturaElectronica.PruebaConsola.localhost.HelloWorldResponse HelloWorld(TestFacturaElectronica.PruebaConsola.localhost.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento factura del espacio de nombres http://tempuri.org/TestFacturaElectronica/WebService/WebService1 no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestFacturaElectronica/WebService/WebService1/ObtenerCAE", ReplyAction="*")]
        TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAEResponse ObtenerCAE(TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1", Order=0)]
        public TestFacturaElectronica.PruebaConsola.localhost.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TestFacturaElectronica.PruebaConsola.localhost.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1", Order=0)]
        public TestFacturaElectronica.PruebaConsola.localhost.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TestFacturaElectronica.PruebaConsola.localhost.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCAERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCAE", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1", Order=0)]
        public TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAERequestBody Body;
        
        public ObtenerCAERequest() {
        }
        
        public ObtenerCAERequest(TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    public partial class ObtenerCAERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestFacturaElectronica.PruebaConsola.localhost.Factura factura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long cuit;
        
        public ObtenerCAERequestBody() {
        }
        
        public ObtenerCAERequestBody(TestFacturaElectronica.PruebaConsola.localhost.Factura factura, long cuit) {
            this.factura = factura;
            this.cuit = cuit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCAEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCAEResponse", Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1", Order=0)]
        public TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAEResponseBody Body;
        
        public ObtenerCAEResponse() {
        }
        
        public ObtenerCAEResponse(TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/TestFacturaElectronica/WebService/WebService1")]
    public partial class ObtenerCAEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestFacturaElectronica.PruebaConsola.localhost.FECAEResponse ObtenerCAEResult;
        
        public ObtenerCAEResponseBody() {
        }
        
        public ObtenerCAEResponseBody(TestFacturaElectronica.PruebaConsola.localhost.FECAEResponse ObtenerCAEResult) {
            this.ObtenerCAEResult = ObtenerCAEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TestFacturaElectronica.PruebaConsola.localhost.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TestFacturaElectronica.PruebaConsola.localhost.WebService1Soap>, TestFacturaElectronica.PruebaConsola.localhost.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFacturaElectronica.PruebaConsola.localhost.HelloWorldResponse TestFacturaElectronica.PruebaConsola.localhost.WebService1Soap.HelloWorld(TestFacturaElectronica.PruebaConsola.localhost.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TestFacturaElectronica.PruebaConsola.localhost.HelloWorldRequest inValue = new TestFacturaElectronica.PruebaConsola.localhost.HelloWorldRequest();
            inValue.Body = new TestFacturaElectronica.PruebaConsola.localhost.HelloWorldRequestBody();
            TestFacturaElectronica.PruebaConsola.localhost.HelloWorldResponse retVal = ((TestFacturaElectronica.PruebaConsola.localhost.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAEResponse TestFacturaElectronica.PruebaConsola.localhost.WebService1Soap.ObtenerCAE(TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAERequest request) {
            return base.Channel.ObtenerCAE(request);
        }
        
        public TestFacturaElectronica.PruebaConsola.localhost.FECAEResponse ObtenerCAE(TestFacturaElectronica.PruebaConsola.localhost.Factura factura, long cuit) {
            TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAERequest inValue = new TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAERequest();
            inValue.Body = new TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAERequestBody();
            inValue.Body.factura = factura;
            inValue.Body.cuit = cuit;
            TestFacturaElectronica.PruebaConsola.localhost.ObtenerCAEResponse retVal = ((TestFacturaElectronica.PruebaConsola.localhost.WebService1Soap)(this)).ObtenerCAE(inValue);
            return retVal.Body.ObtenerCAEResult;
        }
    }
}
