//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestMvcApplication2.Resources.Home.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USER DELETED.
        /// </summary>
        public static string AlertUsuarioEliminado {
            get {
                return ResourceManager.GetString("AlertUsuarioEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are empty fields! Try again..
        /// </summary>
        public static string AlertValidacion1 {
            get {
                return ResourceManager.GetString("AlertValidacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User added successfully.
        /// </summary>
        public static string AlertValidacion2 {
            get {
                return ResourceManager.GetString("AlertValidacion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users detail:.
        /// </summary>
        public static string DetalleInfo1 {
            get {
                return ResourceManager.GetString("DetalleInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact information:.
        /// </summary>
        public static string DetalleInfo2 {
            get {
                return ResourceManager.GetString("DetalleInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email addresses:.
        /// </summary>
        public static string DetalleInfoMail {
            get {
                return ResourceManager.GetString("DetalleInfoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phones:.
        /// </summary>
        public static string DetalleInfoTel {
            get {
                return ResourceManager.GetString("DetalleInfoTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update info.
        /// </summary>
        public static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basic information:.
        /// </summary>
        public static string NuevoInfo1 {
            get {
                return ResourceManager.GetString("NuevoInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact information (optional):.
        /// </summary>
        public static string NuevoInfo2 {
            get {
                return ResourceManager.GetString("NuevoInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check details.
        /// </summary>
        public static string OpcionDetalleUsuario {
            get {
                return ResourceManager.GetString("OpcionDetalleUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New user.
        /// </summary>
        public static string OpcionNuevoUsuario {
            get {
                return ResourceManager.GetString("OpcionNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choice a menu option....
        /// </summary>
        public static string PanelCentralInicial {
            get {
                return ResourceManager.GetString("PanelCentralInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify existing data, and then click &apos;Confirm&apos;..
        /// </summary>
        public static string SubmitModificar {
            get {
                return ResourceManager.GetString("SubmitModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string TApellido {
            get {
                return ResourceManager.GetString("TApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D.N.I. nº.
        /// </summary>
        public static string TDNI {
            get {
                return ResourceManager.GetString("TDNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string TDomicilio {
            get {
                return ResourceManager.GetString("TDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth.
        /// </summary>
        public static string TFechaNac {
            get {
                return ResourceManager.GetString("TFechaNac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Management.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string TLocalidad {
            get {
                return ResourceManager.GetString("TLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail address.
        /// </summary>
        public static string TMail {
            get {
                return ResourceManager.GetString("TMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name.
        /// </summary>
        public static string TNombre {
            get {
                return ResourceManager.GetString("TNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number.
        /// </summary>
        public static string TTelefono {
            get {
                return ResourceManager.GetString("TTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail type.
        /// </summary>
        public static string TTipoMail {
            get {
                return ResourceManager.GetString("TTipoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone type.
        /// </summary>
        public static string TTipoTel {
            get {
                return ResourceManager.GetString("TTipoTel", resourceCulture);
            }
        }
    }
}
